### PR TITLE
GA Snap10.0 - temporary workaround for GemConflict

### PR DESCRIPTION
**Pull request by lpramuk**
GA Snap10.0 - temporary workaround for GemConflict

- FIXME: dont forget to remove once fixed

### CODE REVIEW

**Comment by lpramuk** [comment]
```
...
[root@<fqdn>] run: sed -i 's/0\.0\.16/0.0.14/' /opt/theforeman/tfm/root/usr/share/gems/specifications/hammer_cli_foreman-0.5.1.6.gemspec
...
:: [   PASS   ] :: Command 'fab -H root@<fqdn> product_install:satellite6-DOWNSTREAM,sat_cdn_version=6.2,test_in_stage=false' (Expected 0, got 0)
```

**Comment by omaciel** [comment]
Thank you but NACK. We need a real fix from DEV on this one.

**Comment by lpramuk** [comment]
What you gonna do if a fix will be pending for a week or so?
This is for unblocking us very very quickly

**Comment by lpramuk** [comment]
Hey, this is just temporary... I wont forget about it I swear :-)

Anyway,  I plan to have a proper place in our automation for such type of fixes.

**Comment by rplevka** [comment]
@omaciel , Perhaps we could trigger the automation against @lpramuk branch so we can still benefit from the fix and don't need to push it to master.
However I think our trigger jobs don't support that at the moment.

**Comment by omaciel** [comment]
At this point, if we're blocked because of a regression after a BETA release, we need a real fix from DEV. If it takes them 1 week to deliver it, we slip the GA by 1 week.

**Comment by elyezer** [comment]
We should definitely be more strict until GA.

**Comment by elyezer** [comment]
@lpramuk it seems that this is not needed anymore. Let's close if that is the case.

**Comment by elyezer** [comment]
Closing this since it seems not valid anymore. If needed it can be reopened.

**Pull request closed without merging**
