### PR TITLE
Workaround for pulp message bus connection issue.

### PR DESCRIPTION
**Pull request by sthirugn**
As per the conversation with dev, this workaround will disable katello services
check before proceeding with the async tasks

### CODE REVIEW

**Comment by sthirugn** [comment]
Unable to test because of pycurl issue

**Comment by sthirugn** [comment]
test:
```
fab -H $host -u root -p dog8code set_service_check_status
[$host] Executing task 'set_service_check_status'
[$host] run: hammer -u admin -p changeme settings set --name=check_services_before_actions --value=false
[$host] out: Setting [check_services_before_actions] updated to []
[$host] out: 


Done.
Disconnecting from $hostm... done.
```

**Comment by sthirugn** [comment]
Note: I still had pycurl issues even after trying to use https://github.com/SatelliteQE/automation-tools/pull/339.  So test this, I disabled upgrade tasks in my local.  Anyways this is not a blocker for this PR.

**Comment by sthirugn** [comment]
Ready for review/merge.

**Comment by omaciel** [comment]
ACK

**Comment by lpramuk** [comment]
Cool, satellite 6.1 install was aborted
```
[localhost] Executing task 'set_service_check_status'
[localhost] run: hammer -u admin -p changeme settings set --name=check_services_before_actions --value=false
[localhost] out: Error: No such sub-command 'settings'
```

**Comment by sthirugn** [comment]
@lpramuk yes I saw this error yday, this is non fatal, your 6.1.9 box should still be running.  I will get to this fix shortly.

**Comment by sthirugn** [comment]
this is one of the pains of not branching automation-tools, one should take care of 6.0, 6.1, 6.2 and not just fix latest version and be done with it :)

**Comment by sthirugn** [comment]
@lpramuk addressed in https://github.com/SatelliteQE/automation-tools/pull/343

**Pull request merged**
