### PR TITLE
Add utility to translate jobID to system and its reservation status (+some more info)

### PR DESCRIPTION
**Pull request by jhutar**

### CODE REVIEW

**Comment by Ichimonji10** [comment]
Please squash these two commits down in to one commit:

    git rebase -i HEAD~2
    # in text editor, "pick" first commit, "squash" second commit
    # in text editor, type new commit message
    # in shell, verify commit history is correct
    git push -f origin master

Also, it's a very good idea to check out a new branch before starting work and submitting a pull request. That allows you to work on as many separate projects as you'd like without being blocked on one pull request.

    git checkout -b new-branch
    # edit source code and test changes
    git add ...
    git commit ...
    git push origin new-branch
    # submit pull request from your new-branch branch to upstream's master branch

**Comment by jhutar** [comment]
Thanks! I have squashed these two commits.

**Comment by Ichimonji10** [comment]
I've make some suggested edits and pushed them to a branch at https://github.com/SatelliteQE/automation-tools/compare/master...Ichimonji10:beaker. Here's a diff of changes in the last commit in that branch:

```diff
diff --git a/automation_tools/beaker.py b/automation_tools/beaker.py
index 9f80e16..2d96d22 100644
--- a/automation_tools/beaker.py
+++ b/automation_tools/beaker.py
@@ -1,19 +1,27 @@
 """Tools to work with Beaker (https://beaker-project.org/).
 
-Note that you need `bkr` command available (comes from beaker-client package)
-and configured. See:
+The ``bkr`` command-line utility must be available and configured. (Available
+via the ``beaker-client`` package on Fedora.) See the `Installing and
+configuring the client`_ section of the Beaker documentation.
 
-https://beaker-project.org/docs/user-guide/bkr-client.html#installing-and-configuring-the-client
-"""
+.. _Installing and configuring the client:
+    https://beaker-project.org/docs/user-guide/bkr-client.html#installing-and-configuring-the-client
 
+"""
+import pprint
 import subprocess
 import xml.dom.minidom
 
 
+def main():
+    """Run :func:`beaker_jobid_to_system_info` and print the response."""
+    pprint.pprint(beaker_jobid_to_system_info(open('a.xml')))
+
+
 def _beaker_process_recipe(recipe):
     """Process recipe and return info about it
 
-    :param str recipe: recipe (or guestrecipe) element to process
+    :param recipe: recipe (or guestrecipe) element to process
 
     """
     recipe_info = {}
@@ -24,53 +32,56 @@ def _beaker_process_recipe(recipe):
     recipe_info['arch'] = recipe.attributes['arch'].value
     recipe_info['distro'] = recipe.attributes['distro'].value
     recipe_info['variant'] = recipe.attributes['variant'].value
+
     # Do we have /distribution/reservesys? If so, status is based on that.
-    tasks = recipe.getElementsByTagName("task")
+    tasks = recipe.getElementsByTagName('task')
     for task in reversed(tasks):
         if task.attributes['name'].value == '/distribution/reservesys':
             res_task = task
             break
+
     # Do we have <reservesys>? If so, status is recipe.status.
-    reservesyss = recipe.getElementsByTagName("reservesys")
-    for reservesys in reservesyss:
+    reservesyss = recipe.getElementsByTagName('reservesys')
+    for _ in reservesyss:
         res_tag = True
         break
+
     # Determine status of the recipe/system reservation
     if res_tag and not res_task:
         recipe_info['reservation'] = recipe.attributes['status'].value
     elif res_task and not res_tag:
         recipe_info['reservation'] = res_task.attributes['status'].value
     elif res_task and res_tag:
-        recipe_info['reservation'] = "ERROR: Looks like the recipe " + \
-                                     "for this system have too many " + \
-                                     "methods to reserve. Do not know " + \
-                                     "what happens."
+        recipe_info['reservation'] = (
+            'ERROR: Looks like the recipe for this system have too many '
+            'methods to reserve. Do not know what happens.'
+        )
     else:
         recipe_info['reservation'] = recipe.attributes['status'].value
     return recipe_info
 
 
-def beaker_jobid_to_system_info(jobID):
+def beaker_jobid_to_system_info(job_id):
     """Get system reservation task status (plus other info) based on
-    Beaker jobID.
+    Beaker ``job_id``.
 
     This function requires configured bkr utility. We parse everithing from
-    `bkr job-results [--prettyxml] J:123456`, so if you see some breakage,
+    ``bkr job-results [--prettyxml] J:123456``, so if you see some breakage,
     please capture that output.
 
-    For testing putposes, if you provide file descriptor instead of jobID,
+    For testing putposes, if you provide file descriptor instead of ``job_id``,
     XML will be loaded from there.
 
-    :param str jobID: ID of a Beaker job (e.g. 'J:123456')
+    :param job_id: The ID of a Beaker job. For example: 'J:123456'
 
     """
     systems = []
 
     # Get TML with job results and create DOM object
-    if hasattr(jobID, 'read'):
-        dom = xml.dom.minidom.parse(jobID)
+    if hasattr(job_id, 'read'):
+        dom = xml.dom.minidom.parse(job_id)
     else:
-        out = subprocess.check_output(['bkr', 'job-results', jobID])
+        out = subprocess.check_output(['bkr', 'job-results', job_id])
         dom = xml.dom.minidom.parseString(out)
 
     # Parse the DOM object. The XML have structure like this (all elements
@@ -85,18 +96,18 @@ def beaker_jobid_to_system_info(jobID):
     #     </recipeSet>
     #     <recipeSet id='457' ...
     #       ...
-    jobs = dom.getElementsByTagName("job")
+    jobs = dom.getElementsByTagName('job')
     for job in jobs:
-        recipeSets = job.getElementsByTagName("recipeSet")
-        for recipeSet in recipeSets:
-            recipes = recipeSet.getElementsByTagName("recipe")
+        recipe_sets = job.getElementsByTagName('recipeSet')
+        for recipe_set in recipe_sets:
+            recipes = recipe_set.getElementsByTagName('recipe')
             for recipe in recipes:
                 systems.append(_beaker_process_recipe(recipe))
-                guestrecipes = recipe.getElementsByTagName("guestrecipe")
+                guestrecipes = recipe.getElementsByTagName('guestrecipe')
                 for guestrecipe in guestrecipes:
                     systems.append(_beaker_process_recipe(guestrecipe))
     return systems
 
-if __name__ == "__main__":
-    import pprint
-    pprint.pprint(beaker_jobid_to_system_info(open('a.xml')))
+
+if __name__ == '__main__':
+    main()
```

**Comment by Ichimonji10** [comment]
Some notes on the above:

* Don't put any logic in the `if __name__ == '__main__':` block. Call a `main()` function instead.
* Place all imports at the top of the module.
* Use `lower_case` variable names.
* Use single quotes. It's the convention in much of our code base and adhering to it makes reading code easier to do.
* None of the documentation in the `automation_tools` package is currently parsed by the Sphinx documentation generator. Nevertheless, I've fiddled with documentation to make it adhere to the reST syntax as well as possible and to be forward-compatible for when Sphinx is used.
* Drop unused variables, or use a placeholder variable like `_`.
* Make use of automatic string concatenation. (Search for "Looks like the recipe for".)
* Use whitespace and comments to clearly delineate logical sections of code.

**Comment by Ichimonji10** [comment]
One thing I did *not* address is the `res_task` variable. Pylint gives this warning:

    E: 53,37: Instance of 'bool' has no 'attributes' member (no-member)

And pylint is correct in giving that warning. The variable is initially declared as a boolean but then re-used as an... object of some other kind? It's unclear. Can you please refactor code so that the `res_task` variable has a single type? It's rarely a good idea to make a variable take on multiple types, except in some very specific cases.

**Comment by Ichimonji10** [comment]
By the way - you can copy and paste the raw diff I posted above and apply it directly. Just download the diff and save it in a file, and then:

    git apply my-diff-file

**Comment by jhutar** [comment]
Thanks for the changes!

I do not agree with the one of them though where you are moving code from `if __name__ == '__main__':` block. Wouldn't it be confusing to have `main` function in a library? That code serves as a unit test (it have hardcoded filename, so consider it manual test of the function)?

**Comment by jhutar** [comment]
Another question: when I apply your change, do you want to me to squash that commit as well? That way you would loose authorship, or am I missing something?

**Comment by Ichimonji10** [comment]
Go ahead and squash things. I don't particularly care about ownership in this case.

**Comment by jhutar** [comment]
I was confused about your comment about Pylint: that check is not included in the Travis check? I have installed that and now I can see the complaint. Thanks.

**Comment by Ichimonji10** [comment]
You're correct: Travis does not use pylint. Hopefully we will run Pylint as part of the Travis check someday. That would be a definite improvement that will help to prevent many, many issues. I suggest you start using the tool - you'll be amazed at how many errors and warnings it emits. And they're legit, too.

Anyway. Please go ahead and fix the `res_task` typing mismatch.

**Comment by jhutar** [comment]
OK, ignore mine comment https://github.com/SatelliteQE/automation-tools/pull/201#issuecomment-121344354. This is more your project than mine, so I respect your opinion.

**Comment by Ichimonji10** [comment]
Eh, it's a good question that's worth answering anyway.

> I do not agree with the one of them though where you are moving code from `if __name__ == '__main__':` block. Wouldn't it be confusing to have `main` function in a library? That code serves as a unit test (it have hardcoded filename, so consider it manual test of the function)?

You have a "main" function in the new module. The difference is that I'm suggesting you explicitly label your "main" function as such so that it can be mocked out, unit tested, and easily recognized by other developers as being a "main" function.

**Comment by jhutar** [comment]
With this both pylint and flake8 are passing. Your feedback incorporated. Thanks!

**Comment by Ichimonji10** [comment]
ACK

Thank you very much for being so responsive to my requests.

**Comment by jhutar** [comment]
Thanks to you

**Comment by elyezer** [comment]
ACK, thank you @jhutar for this PR.

About the tests, we don't do that because most of the things here is to run a set of the commands on the server, but there are some methods that worth testing and we don't do that. The methods that serve as helpers should be tested in some way so we can ensure that it does not create something not expected on the server.

**Comment by Ichimonji10** [comment]
Karma given.

**Pull request merged**
