### PR TITLE
Improve setup_proxy task

### PR DESCRIPTION
**Pull request by elyezer**
Allow the setup_proxy setup a non-authenticated proxy. To do that, the
username and password expected in the proxy URL can be omitted. Also run
it on product_install if the PROXY_INFO environment variable is set.

### CODE REVIEW

**Comment by Ichimonji10** [comment]
APT

**Comment by omaciel** [comment]
ACK

**Comment by omaciel** [comment]
```log
17:55:07 omaciel: elyezer++
17:55:08 robottelo: elyezer has 482 points
```

**Comment by elyezer** [comment]
@omaciel thanks

**Pull request merged**
