### PR TITLE
Attemp #2 to mitigate "Error: INVALID_ZONE"

### PR DESCRIPTION
**Pull request by lpramuk**
Attemp No.2 to mitigate "Error: INVALID_ZONE"
- check for permanent zones (--permanent) since we check/modify the permanent ones
- restart firewalld service and wait (mere waiting doesn't help)

### CODE REVIEW

**Comment by lpramuk** [comment]
attempt #1 was merged as PR #405

**Comment by omaciel** [comment]
@kbidarkar mind reviewing this when you have a chance?

**Comment by lpramuk** [comment]
I hit it today, so it forced me to test it and I happened to resolved it by these changes.

At last we need to get rid of katellovirt module which is causing this (interaction with firewalld).
We better install libvirt by set of cmds that we control over easily.

**Comment by kbidarkar** [comment]
@lpramuk, I just checked the jobs to find the issue where we could see this with logs, but didn't find one. While using which job did you face this issue? It's seems to be working fine currently for the jobs.

**Comment by kbidarkar** [comment]
But, yeah we would need to use the "permanent" option to firewall-cmd as we are updating the firewall ports for persist-ency across reboot.

**Comment by lpramuk** [comment]
this issue arises if you are reusing machine or your instance is not clean OS install.
Mainly in satellite6 installer (not in automation)

**Comment by kbidarkar** [comment]
I think, currently we do not provide support for reusing a machine with jenkins jobs, without re-installing the OS.
There was no such effort since the beginning and we need to work towards it if we need to provide support for it to happen.

Anyways, we require this, as this would correct the current commands being used.

ACK

**Pull request merged**
