### PR TITLE
Added support to provision Sat6 VMs using static ips & VLAN Bridges

### PR DESCRIPTION
**Pull request by kbidarkar**
*) Now setup_ddns will run only when VM uses a dhcp IP via br0
   Bridge.
*) Dynamic DNS is not required when we provide the VM with a static
   Ip address via VLAN Bridges.
*) The idea is to ask the DNS configured beforehand.

### CODE REVIEW

**Comment by sghai** [comment]
Changes Looks good. Assuming VM's Hostname and static IP binding is done.

**Comment by kbidarkar** [comment]
Yup.
VM's Hostnames have been added to IPA server which exists in RDULab.
Static IP binding is done in Jenkins --> provisioning Config File

**Comment by sghai** [comment]
:+1:

**Comment by elyezer** [comment]
Looks good. ACK

**Pull request merged**
