### PR TITLE
Fix the foreman_key_file path

### PR DESCRIPTION
**Pull request by kbidarkar**
*) Fixed the foreman_key_file path, by excluding the username
   foreman from it.
*) As foreman user's home_dir is /usr/share/foreman/

### CODE REVIEW

**Comment by elyezer** [comment]
ACK

**Comment by kbidarkar** [comment]
Fix for https://github.com/SatelliteQE/automation-tools/issues/290

**Comment by abalakh** [comment]
ACK

**Comment by lpramuk** [comment]
NACK

**Comment by elyezer** [comment]
The fix is gonna work I did some manual testing and got:

```
[root@qe-sat6-rhel7 ~]# sudo -u foreman /bin/bash -l -c "ls -l ~/.ssh/id_rsa"
-rw-------. 1 foreman foreman 3243 Nov 23 12:17 /usr/share/foreman/.ssh/id_rsa
```

Thanks for the fix @kbidarkar

**Pull request merged**
