### PR TITLE
fake capsule needs to use nmap's ncat

### LINKED ISSUE #382: fake capsule needs to use nmap's ncat
As we utilize nc ```-c``` option for capsule mocking and this option is available only with nmap's ncat.
On rhel6 provided by ```nmap``` rpm
On rhel7 provided by ```nmap-ncat``` rpm aliased as ```nc```

### PR DESCRIPTION
**Pull request by lpramuk**
fake capsule needs to use nmap's ncat
* modified setup_alternate_capsule_ports() to prepare nmap's ncat (fixing rhel6)

(Fixes #382)

### CODE REVIEW

**Comment by rplevka** [comment]
ACK

**Comment by sghai** [comment]
@lpramuk : looks good. Could you please add a comment there as why we made this change ?

**Comment by rplevka** [comment]
@sghai - due to `nc` command provided on `RHEL6` does not support `-c` option which we need.
```
$ ncat --help
...
-c, --sh-exec <command>    Executes the given command via /bin/sh
...
```

**Comment by sghai** [comment]
@rplevka : thanks.. know why we made this change but wanted to have this as comment in code :)

**Comment by lpramuk** [comment]
Comments resolved by adding comments :)

**Comment by sghai** [comment]
Thanks @lpramuk .

**Pull request merged**
