### PR TITLE
Implement possibility to validate manifest

### PR DESCRIPTION
**Pull request by jhutar**
Fixes https://github.com/SatelliteQE/automation-tools/issues/786

This is how config file would look like:

```
$ cat config/robottelo-manifest-content.conf 
# This file contains subscription names (one per line) expected in robottelo-automation manifest.
# Subscriptions named here must be in the manifest and no other subs are allowed.
Red Hat Beta Access
Red Hat Enterprise Linux for Virtual Datacenters, Premium
Red Hat Enterprise Linux Server, Premium (8 sockets) (Unlimited guests)
Red Hat Enterprise Linux Server, Premium (Physical or Virtual Nodes)
Red Hat Satellite Infrastructure Subscription
```

### CODE REVIEW

**Comment by san7ket** [comment]
Where are we keeping the manifets config file ? In jenkins-config?

**Comment by jhutar** [comment]
Yeah, that robottelo-manifest-content.conf would be in jenkins-config + change would be needed in robottelo-ci where we would `export EXP_SUBS_FILE=config/robottelo-manifest-content.conf` and that would enable this check.

**Comment by rplevka** [comment]
Hi are you in touch with @schlupov? She was working in implementing the method to validate the attached subs. Just to make sure you're not duplicating efforts.

**Comment by jhutar** [comment]
Hello @schlupov, do you have something?

**Comment by san7ket** [comment]
I will add this to resource verification check and the manifest will be validated before the pipeline begins I will try to make the pipeline wait until all the resources are available and asserted.

**Comment by jhutar** [comment]
@san7ket Hello. Once this is merged, I'll happily work in robottelo-ci (to change manifest download job) and in jenkins-configs (to provide a config file), but if you want to do that, feel free.

I do not understand what do you mean with "pipeline wait until all the resources are available"?

**Comment by san7ket** [comment]
@jhutar nah , this would be different, I am planning to add checks in trigger jobs itself. 

I would also like to add one the check to validate the manifest.

**Comment by rplevka** [comment]
@jhutar 
https://github.com/SatelliteQE/automation-tools/pull/788

**Comment by jhutar** [comment]
@rplevka Hey, looks like I was few hours faster than Silvie :) Anyway, I assume Silvie wont work on her PR now. In Silvie's PR it is checking consumer's subscriptions on Portal before downloading it (touching Portal twice), in my I'm checking actual manifest and check is optional. Of course I prefer mine PR, but if you prefer Silvie's, let me know.

**Comment by rplevka** [comment]
@jhutar checking the subs on portal was my idea - It allows us to do the check before we actually download something - i personally find such approach much cleaner (assuming the `download` operation is the most expensive one in the method).

**Comment by jhutar** [comment]
This is how it looks like:

```
(venv) [pok@localhost automation-tools]$ source config/fake_manifest.conf
(venv) [pok@localhost automation-tools]$ source config/subscription_config.conf 
WARNING: env variable DISTRO should be set
WARNING: env variable SATELLITE_VERSION should be set
(venv) [pok@localhost automation-tools]$ EXP_SUBS_FILE=config/robottelo-manifest-content.conf fab -D -H "root@${MANIFEST_SERVER_HOSTNAME}" relink_manifest
[root@sesame.lab.eng.rdu2.redhat.com] Executing task 'relink_manifest'
[root@sesame.lab.eng.rdu2.redhat.com] run: mktemp --suffix=.zip
[root@sesame.lab.eng.rdu2.redhat.com] out: /tmp/tmp.u2YbqU7LGM.zip
[root@sesame.lab.eng.rdu2.redhat.com] out: 

[root@sesame.lab.eng.rdu2.redhat.com] run: curl -sk -X PUT -H "Authorization:Basic cmhzYXRxZTo4dENrOTU5Qk1Hc1l4V0t5" https://subscription.rhsm.redhat.com/subscription/consumers/c36c3a9a-40e8-468a-9069-9510697e369e/certificates?lazy_regen=false
[root@sesame.lab.eng.rdu2.redhat.com] run: curl -sk -H "Authorization:Basic cmhzYXRxZTo4dENrOTU5Qk1Hc1l4V0t5" https://subscription.rhsm.redhat.com/subscription/consumers/c36c3a9a-40e8-468a-9069-9510697e369e/export/ -I
[root@sesame.lab.eng.rdu2.redhat.com] out: HTTP/1.1 200 OK
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: Server: Apache-Coyote/1.1
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: x-candlepin-request-uuid: 4ec7f8f1-60c6-439a-b2f3-bf885f002898
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: Content-Disposition: attachment; filename=c36c3a9a-40e8-468a-9069-9510697e369e-export.zip
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: X-Version: 2.3.17-1
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: Content-Type: application/zip
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: Transfer-Encoding: chunked
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: Date: Thu, 11 Jul 2019 07:04:29 GMT
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: 

[root@sesame.lab.eng.rdu2.redhat.com] run: curl -sk -H "Authorization:Basic cmhzYXRxZTo4dENrOTU5Qk1Hc1l4V0t5" https://subscription.rhsm.redhat.com/subscription/consumers/c36c3a9a-40e8-468a-9069-9510697e369e/export/ -o /tmp/tmp.u2YbqU7LGM.zip
expected subscriptions in /tmp/tmp.u2YbqU7LGM.zip are Red Hat Enterprise Linux for Virtual Datacenters, Premium & Red Hat Enterprise Linux Server, Premium (Physical or Virtual Nodes) & Red Hat Satellite Infrastructure Subscription & Red Hat Enterprise Linux Server, Premium (8 sockets) (Unlimited guests) & Red Hat Beta Access
[root@sesame.lab.eng.rdu2.redhat.com] run: rct cat-manifest --no-content /tmp/tmp.u2YbqU7LGM.zip
[root@sesame.lab.eng.rdu2.redhat.com] out: [...]

current subscriptions in /tmp/tmp.u2YbqU7LGM.zip are Red Hat Enterprise Linux for Virtual Datacenters, Premium & Red Hat Enterprise Linux Server, Premium (Physical or Virtual Nodes) & Red Hat Satellite Infrastructure Subscription & Red Hat Enterprise Linux Server, Premium (8 sockets) (Unlimited guests) & Red Hat Beta Access
[root@sesame.lab.eng.rdu2.redhat.com] run: mv /tmp/tmp.u2YbqU7LGM.zip /opt/manifests/manifest-20190711.zip
[root@sesame.lab.eng.rdu2.redhat.com] run: chmod 644 /opt/manifests/manifest-20190711.zip
[root@sesame.lab.eng.rdu2.redhat.com] run: restorecon -v /opt/manifests/manifest-20190711.zip
[root@sesame.lab.eng.rdu2.redhat.com] out: Relabeled /opt/manifests/manifest-20190711.zip from unconfined_u:object_r:user_tmp_t:s0 to unconfined_u:object_r:usr_t:s0
[root@sesame.lab.eng.rdu2.redhat.com] out: 

[root@sesame.lab.eng.rdu2.redhat.com] run: unlink /opt/manifests/manifest-latest.zip
[root@sesame.lab.eng.rdu2.redhat.com] run: ln -s /opt/manifests/manifest-20190711.zip /opt/manifests/manifest-latest.zip

Done.
Disconnecting from root@sesame.lab.eng.rdu2.redhat.com... done.
```

When that variable is not set, all works without that check:

```
(venv) [pok@localhost automation-tools]$ unset EXP_SUBS_FILE
(venv) [pok@localhost automation-tools]$ fab -D -H "root@${MANIFEST_SERVER_HOSTNAME}" relink_manifest
[root@sesame.lab.eng.rdu2.redhat.com] Executing task 'relink_manifest'
[root@sesame.lab.eng.rdu2.redhat.com] run: mktemp --suffix=.zip
[root@sesame.lab.eng.rdu2.redhat.com] out: /tmp/tmp.SZganZzmAa.zip
[root@sesame.lab.eng.rdu2.redhat.com] out: 

[root@sesame.lab.eng.rdu2.redhat.com] run: curl -sk -X PUT -H "Authorization:Basic cmhzYXRxZTo4dENrOTU5Qk1Hc1l4V0t5" https://subscription.rhsm.redhat.com/subscription/consumers/c36c3a9a-40e8-468a-9069-9510697e369e/certificates?lazy_regen=false
[root@sesame.lab.eng.rdu2.redhat.com] run: curl -sk -H "Authorization:Basic cmhzYXRxZTo4dENrOTU5Qk1Hc1l4V0t5" https://subscription.rhsm.redhat.com/subscription/consumers/c36c3a9a-40e8-468a-9069-9510697e369e/export/ -I
[root@sesame.lab.eng.rdu2.redhat.com] out: HTTP/1.1 200 OK
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: Server: Apache-Coyote/1.1
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: x-candlepin-request-uuid: 830ed409-e4b9-4648-ac56-62b832c42553
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: Content-Disposition: attachment; filename=c36c3a9a-40e8-468a-9069-9510697e369e-export.zip
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: X-Version: 2.3.17-1
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: Content-Type: application/zip
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: Transfer-Encoding: chunked
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: Date: Thu, 11 Jul 2019 07:07:26 GMT
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: 
[root@sesame.lab.eng.rdu2.redhat.com] out: 

[root@sesame.lab.eng.rdu2.redhat.com] run: curl -sk -H "Authorization:Basic cmhzYXRxZTo4dENrOTU5Qk1Hc1l4V0t5" https://subscription.rhsm.redhat.com/subscription/consumers/c36c3a9a-40e8-468a-9069-9510697e369e/export/ -o /tmp/tmp.SZganZzmAa.zip
[root@sesame.lab.eng.rdu2.redhat.com] run: mv /tmp/tmp.SZganZzmAa.zip /opt/manifests/manifest-20190711.zip
[root@sesame.lab.eng.rdu2.redhat.com] run: chmod 644 /opt/manifests/manifest-20190711.zip
[root@sesame.lab.eng.rdu2.redhat.com] run: restorecon -v /opt/manifests/manifest-20190711.zip
[root@sesame.lab.eng.rdu2.redhat.com] out: Relabeled /opt/manifests/manifest-20190711.zip from unconfined_u:object_r:user_tmp_t:s0 to unconfined_u:object_r:usr_t:s0
[root@sesame.lab.eng.rdu2.redhat.com] out: 

[root@sesame.lab.eng.rdu2.redhat.com] run: unlink /opt/manifests/manifest-latest.zip
[root@sesame.lab.eng.rdu2.redhat.com] run: ln -s /opt/manifests/manifest-20190711.zip /opt/manifests/manifest-latest.zip

Done.
Disconnecting from root@sesame.lab.eng.rdu2.redhat.com... done.
```

**Pull request merged**
