### PR TITLE
Fix distro_info execution on product_install task

### PR DESCRIPTION
**Pull request by elyezer**
As product install can run the tasks on the specified server on in a
virtual machine created, because this tasks should be executed using the
execute function. Execute distro_info on the correct host.

### CODE REVIEW

**Comment by elyezer** [comment]
This kind of mistake should not happen in the future, have been a long time without dealing with product install execution model.

**Comment by JacobCallahan** [comment]
APT

**Comment by Ichimonji10** [comment]
ACK

**Comment by Ichimonji10** [comment]
For reference:

> \<ichimonji10> elyezer: The dict returned only has one item?
> \<elyezer> ichimonji10: in that case yes

**Pull request merged**
