### PR TITLE
[Do Not Merge] Fix repo_install as RHEL6 has also optional channel available

### PR DESCRIPTION
**Pull request by lpramuk**
Fix repo_install as RHEL6 has also optional channel available
(...if optional is not available then entitlements are about to fix)

(Issue #416)

### CODE REVIEW

**Comment by kbidarkar** [comment]
Are you able to install grub2-efi package from rhel6 optional-rpms repo ?

If not, do you know from which repo we can find it out ?

**Comment by kbidarkar** [comment]
The exact package name is `grub2-efi-modules`.

**Comment by lpramuk** [comment]
rhel-6-server-optional-rpms doesnt have it while rhel-7-server-optional-rpms has:
```grub2-efi-modules.x86_64                         1:2.02-0.34.el7_2                          @rhel-7-server-optional-rpms```

**Comment by lpramuk** [comment]
so it has to be contained by Satellite compose then (on rhel6)

**Comment by lpramuk** [comment]
but I dont see currently foreman, foreman-plugins for rhel6
Thus we dont have to solve it (at least for now)

**Comment by kbidarkar** [comment]
@lpramuk , thanks for investigating into this task.

**Pull request closed without merging**
