### PR TITLE
Improve iso_download task

### PR DESCRIPTION
**Pull request by elyezer**
Append / if the url does not ends with .iso and does not have it in
other to urljoin not drop the last section.

### CODE REVIEW

**Comment by sthirugn** [comment]
ACK, but not sure why we need to support directory path here.  Cant we just make it a requirement to supply the direct .iso link?

**Comment by omaciel** [comment]
ACK and merge (the explanation will be provided as a comment but it won't block the merge)

**Comment by elyezer** [comment]
@sthirugn by accepting the directory path a generic URL can be provided for the trigger job and we are able to generate URL for the iso and downstream jobs.

**Comment by sthirugn** [comment]
@elyezer ty

**Pull request merged**
