### PR TITLE
fixed the pattern for abrt setup

### PR DESCRIPTION
**Pull request by tkolhar**
please review it
thanks

 cat file.txt
#SSLVerify = no
#SSLClientAuth =

 sed -i -e "s|#SSLVerify = no.*|SSLVerify = yes|" file.txt
 cat file.txt
SSLVerify = yes
#SSLClientAuth =

### CODE REVIEW

**Comment by Ichimonji10** [comment]
Can you provide some context for this PR, @tkolhar? I well understand the regular expression. But what will this change impact? Is the `setup_abrt` task used when provisioning upstream? Downstream? Does `setup_abrt` not work right now? Can you give an example of what the configuration file looks like? The change itself looks sane, but I would like some contextual information here.

**Comment by tkolhar** [comment]
@Ichimonji10 , the pattern s/^SSLClientAuth = .*/SSLClientAuth = puppet/ is not working in upstream
so i had to modify the pattern s|#SSLClientAuth = .*|SSLClientAuth = puppet| . requesting you
to please let me know if it is clear know . thanks.

**Comment by elyezer** [comment]
This will fail too because there is a space after `#`, grabbed this from the config file:

```conf
# no means that ssl certificates will not be checked
# SSLVerify = no

...

# Using Puppet certificate:
# SSLClientAuth = puppet
```

**Comment by elyezer** [comment]
Tried manually:

```shell
$ sed -e "s|#SSLVerify = no.*|SSLVerify = yes|" /etc/libreport/plugins/ureport.conf
...

# no means that ssl certificates will not be checked
# SSLVerify = no

...
```

With the space:

```shell
$ sed -e "s|# SSLVerify = no.*|SSLVerify = yes|" /etc/libreport/plugins/ureport.conf
...

# no means that ssl certificates will not be checked
SSLVerify = yes

...
```

Also in this case using `/` or `|` as a separator does not make any difference. Be aware that I have removed the `-i` parameter from my example because that flag, when present, edit the file in place and does not output anything.

**Pull request closed without merging**
