### PR TITLE
Real fix for Bug 1329394 - Skip oscap install for rhel 6

### PR DESCRIPTION
**Pull request by sthirugn**

### CODE REVIEW

**Comment by sthirugn** [comment]
There is no other QE available online at this time :/

I am merging this to retrigger rhel 6 automation.

**Comment by omaciel** [comment]
@sthirugn why we're not checking for Satellite 6.2 anymore and only for 6.1? So we always want to run `install_puppet_scap_client` but only run `setup_oscap` fro RHEL 7?

**Comment by elyezer** [comment]
Running `distro_info` that way is actually running on the machine where is provisioning the satellite server, not on the server at all. I'm working on a fix.

**Comment by elyezer** [comment]
Sent PR #328 to fix this.

**Comment by sthirugn** [comment]
@omaciel: Yes. The summary is: 
* for 6.0 we don't even run setup_oscap because it is not supported
* for 6.1, we install oscap packages separately
* for 6.2, we use the installer to install
* due to open bug, temporarily we skip installing oscap in rhel 6
ping me if you have more questions :)

**Comment by omaciel** [comment]
@sthirugn so we only want to run `install_puppet_scap_client` for 6.1 and not for 6.0 (unsupported) or 6.2 (use the installer instead)? Seems that the conditional statement will run `install_puppet_scap_client` for 6.2 as well, which confuses me a bit :/

**Comment by sthirugn** [comment]
you are right and this is how it works now.  afaik @kbidarkar is yet to do some refactoring around install_puppet_scap_client()

**Pull request merged**
