### PR TITLE
Removed old Upgrade code from automation_tools init file

### PR DESCRIPTION
**Pull request by jyejare**
This PR includes:
1. Remove old Upgrade Automation Tools code from automation_tools/__init__.py file as we have separate package/directory for python with its own modules.
2. The capsule upgrade command fix for capsule cert option which is now changed to --capsule-certs-tar for 6.2

### CODE REVIEW

**Comment by elyezer** [comment]
Is fabfile needed to be updated?

ACK, pending question.

**Comment by jyejare** [comment]
@elyezer OMG , Yes !

**Comment by sthirugn** [comment]
ACK pending @elyezer's question

**Comment by jyejare** [comment]
Nope, That doesnt requires any fabfile change. That change has been already done in PR #331.

**Pull request merged**
