### PR TITLE
downstream-nightly uses foreman-proxy prefix for puppet

### PR DESCRIPTION
**Pull request by kbidarkar**

### CODE REVIEW

**Comment by sghai** [comment]
ACK

**Comment by san7ket** [comment]
ACK

**Comment by lpramuk** [comment]
if downstream-nightly uses foreman-proxy prefix for puppet then 6.3 will also use it 
then why it is in condition ?

**Comment by kbidarkar** [comment]
probably yes, we may be 100% sure once official 6.3 builds arrive, but what I did in this PR was just revert it back to previous state.

**Pull request merged**
