### PR TITLE
Enable RH Inventory upload

### PR DESCRIPTION
**Pull request by lhellebr**

### CODE REVIEW

**Comment by lhellebr** [comment]
The parameter name has changed apparently in 6.8. Do not merge yet.

**Comment by lhellebr** [comment]
I've fixed this to work with both 6.7 and 6.8. Behavior for other versions should stay the same.

Note that this causes the installation to fail for 6.8 due to [0] but I'd prefer to push this anyway since 6.8 is not yet in automation so nothing will get broken - and the BZ can be expected to be fixed soon.

[0] https://bugzilla.redhat.com/show_bug.cgi?id=1834302

**Comment by lpramuk** [comment]
Once the following error is fixed in the Product we can merge this PR:
```
 Execution of '/bin/yum -d 0 -e 0 -y install tfm-rubygem-foreman_rh_cloud' returned 1: Error: Nothing to do
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/execution.rb:297:in `execute'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/provider.rb:101:in `execute'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/provider/package/yum.rb:223:in `install'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type/package.rb:92:in `block (3 levels) in <module:Puppet>'
```

**Comment by lhellebr** [comment]
@lpramuk Added BZ open conditional

**Comment by lhellebr** [comment]
@lpramuk Can we merge this?

**Pull request merged**
