### PR TITLE
Client Registeration race condition fix with time sleeps

### PR DESCRIPTION
**Pull request by jyejare**
This will fix the race condition issue happening during registering many clients at a time.

### CODE REVIEW

**Comment by jyejare** [comment]
@rplevka , Even though there is bug regarding generating multiple clients at a time, but this is not a real time scenario with customers. And so keeping sleeps will make it at most equal to customer scenarios and even 5 seconds of sleep is much smaller.

**Comment by rplevka** [comment]
@jyejare i'm not asking you to remove the `sleep`, just asking you to decorate that workaround properly.

**Comment by sghai** [comment]
ACK

**Comment by rplevka** [comment]
ACK

**Pull request merged**
