### PR TITLE
Generate foreman debug after upgrade

### PR DESCRIPTION
**Pull request by jyejare**
Generates Foreman Debug at the end of upgrade. So that it can be download as build artefacts in Jenkins.

### CODE REVIEW

**Comment by Ichimonji10** [comment]
ACK

Do we have any way of testing this change before merging it?

**Comment by jyejare** [comment]
@Ichimonji10, I can share the list in /tmp directory. The file will generate there.

**Comment by Ichimonji10** [comment]
@jyejare That's fine. I'm OK knowing that you've done some manual testing.

**Comment by jyejare** [comment]
@Ichimonji10 , Yeah I run it upgrade automation from my system:

This is the Snapshot of Success:
```
[sat6-qe-rhel7.usersys.redhat.com] Executing task 'foreman_debug'
[sat6-qe-rhel7.usersys.redhat.com] download: /home/jyejare/Desktop/RedHat/ToolsTop/automation-tools/satellite.tar.xz <- /tmp/satellite/satellite.tar.xz
Satellite release: cat: /etc/yum.repos.d/satellite.repo: No such file or directory

Done.
Disconnecting from sat6-qe-rhel7.usersys.redhat.com... done.
Disconnecting from 10.8.50.240... done.
You have new mail in /var/mail/root
[root@jyejare automation-tools]# ls
automation_tools  docs  fabfile.py  fabfile.pyc  LICENSE  README.rst  requirements.txt  satellite.tar.xz  setup.py
```

**Comment by sghai** [comment]
ACK pending a query:
Can we get the logs via jenkins web URL or do we need to get that from specific system ?

**Comment by jyejare** [comment]
@sghai , I can point to jenkins logs only after this PR will be merged :) 
Above I have pasted some end logs(not full) form my system. Which indicates the foreman debug file created on satellite server and has been downloaded in running system. Which I will archive it as build artefact in jenkins.

**Comment by sghai** [comment]
ACK

**Comment by elyezer** [comment]
:+1:

**Pull request merged**
