### PR TITLE
Install ansible-foreman_scap_client

### PR DESCRIPTION
**Pull request by san7ket**

### CODE REVIEW

**Comment by lpramuk** [comment]
This role should be installed by default so no need for such task.
If not installed by default file a BZ

**Comment by lpramuk** [comment]
```
# yum list ansiblerole-*
Installed Packages
ansiblerole-insights-client.noarch                                                                              1.6-2.el7sat                                                                             @satellite
Available Packages
ansiblerole-foreman_scap_client.noarch                                                                          0.0.2-1.el7sat                                                                           satellite 
```
Hm, I'm going to file a BZ for that and we can add condition if_bz_open ... and accept PR to unblock your testing

**Comment by lpramuk** [comment]
Oh common you filed BZ a week ago for this :D
https://bugzilla.redhat.com/show_bug.cgi?id=1707325

**Comment by san7ket** [comment]
Thanks for filling BZ , i was going to discuss and then file one. But, yea doesn't harm.

**Comment by san7ket** [comment]
We don't need that task at all, So figured let's re-purpose it. 
I will file a ticket for 6.1, 6.2 cleanup from automation tools,

**Comment by san7ket** [comment]
Please re-visit

**Comment by san7ket** [comment]
@lpramuk please revisit

**Pull request merged**
