### PR TITLE
Update accepted Sat GA versions

### PR DESCRIPTION
**Pull request by JacobCallahan**
Now accepts up to 6.6

### CODE REVIEW

**Comment by pgagne** [comment]
@JacobCallahan I think we also need to take a look at the version of ansible we install during the cdn install
https://github.com/SatelliteQE/automation-tools/blob/21ad57484202257f6a486f7d7f94363b9461eca2/automation_tools/repository.py#L165-L167

`rhel-7-server-ansible-2.8-rpms` is now avaliable for rhel7 so i think we should use it, it is what is recommended in the install docs.

**Comment by JacobCallahan** [comment]
@pgagne that is a separate issue that someone can take up. This is targetted just for getting GA builds going.

**Comment by pgagne** [comment]
@JacobCallahan I disagree, all I saying is we need to make sure that the automation matches what the docs say:
https://access.redhat.com/documentation/en-us/red_hat_satellite/6.6/html/installing_satellite_server_from_a_connected_network/installing_satellite_server#configuring-repositories_satellite

Can you change the ansible repo to `rhel-7-server-ansible-2.8-rpms` as part of this PR.

**Comment by JacobCallahan** [comment]
@pgagne that's a bit of scope-creep, but updated.

**Pull request merged**
