### PR TITLE
Updating pxe template with hostname instead of IP

### PR DESCRIPTION
**Pull request by sghai**
I realized on our automation machines template is being updated with IP of server. Ideally it should be updated with hostname.

### CODE REVIEW

**Comment by Ichimonji10** [comment]
`env['host']` appears in four other locations in the same module. Should those other occurences also be updated?

**Comment by sghai** [comment]
I don't think we need to update other locations because we need this change only for `setup_foreman_discovery`

**Comment by Ichimonji10** [comment]
OK. ACK

**Comment by sthirugn** [comment]
ACK

**Pull request merged**
