### PR TITLE
Added support for configuring AD External Authentication.

### PR DESCRIPTION
**Pull request by kbidarkar**
a) We can now enroll Satellite6 Server to AD
b) We can now configure Satellite6 Server for AD External Auth.

### CODE REVIEW

**Comment by kbidarkar** [comment]
a) Enrolling sat6 server to AD, Test results : http://pastebin.test.redhat.com/457260
b) Configuring Sat6 server for External authentication: http://pastebin.test.redhat.com/457266
For a) and b) , couldn't get things to work in one go , had to fix few things, from time to time. 
And it's hard to keep testing every-time on a fresh setup. Anyways this won't break any existing code, so I think we are good to go.
If any fixes are required, will fix it ASAP.

**Comment by sghai** [comment]
Looks sane from code perspective but I'm not known to idm cmds.

**Comment by kbidarkar** [comment]
@san7ket , Can you please take a look at this PR when you get a chance, you can take a look from the idm cmds perspective.

**Comment by san7ket** [comment]
Checked the commands, all steps and commands looks good

**Pull request merged**
