### PR TITLE
Add information about how to proper install pycurl

### LINKED ISSUE #337: setting env PYCURL_SSL_LIBRARY in setup.py fixes nothing
PYCURL_SSL_LIBRARY has to be set in parent environment to make it actually work.
In setup.py it is useless

### PR DESCRIPTION
**Pull request by elyezer**
Remove the not working fix to install pycurl from setup.py and provide
information on how to install pycurl on the docs.

Close #337

### CODE REVIEW

**Comment by lpramuk** [comment]
another way is to install all at once like that:
```
PYCURL_SSL_LIBRARY={nss|openssl} pip install -U -r requirements.txt
```

**Comment by lpramuk** [comment]
With auto-parsing of curl output:
```
PYCURL_SSL_LIBRARY=$(curl -V | sed -n 's/.*\(NSS\|OpenSSL\).*/\L\1/p') pip install -U -r requirements.txt
```

**Comment by elyezer** [comment]
I tried the suggestion and got the following:

```
bash -c "$(curl -V | sed -n 's/.*\(NSS\|OpenSSL\).*/\L\1/p')"
bash: nss: command not found
```

Same happens by running on zsh:

```
$(curl -V | sed -n 's/.*\(NSS\|OpenSSL\).*/\L\1/p')          
zsh: nss: command not found...
```

**Comment by sthirugn** [comment]
ACK

**Pull request merged**
