### PR TITLE
Remove sat6.3 to be run as INTERNAL, when we have INTERNAL_AK

### PR DESCRIPTION
**Pull request by kbidarkar**
Signed-off-by: Kedar Bidarkar <kbidarka@redhat.com>

### CODE REVIEW

**Comment by JacobCallahan** [comment]
Would this mean I can't provide an internal compose url to the installer job, if I'm trying to install 6.3?

**Comment by omaciel** [comment]
@JacobCallahan I believe this change only affects jobs using the `INTERNAL AK` parameter

**Comment by lpramuk** [comment]
This means that for 6.3 default is INTERNAL_AK

**Comment by lpramuk** [comment]
Merged-in-by: Lukas Pramuk lpramuk@redhat.com

**Comment by kbidarkar** [comment]
This means,
1) `INTERNAL`, `INTERNAL AK` and `INTERNAL REPOFILE` would work from sat6.3+
2) ONLY `INTERNAL` for Sat6.1 and Sat6.2, not the other 2 options.

**Pull request merged**
